# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60fd559e251d5aacca0f0b67a1a977eb370ff3363b8ff56feaad341873fa82323a529ad5f75d3cf5154c32443e52f1b4fe476f4bfb65240328efe2c25f34f583

test:
  secret_key_base: 597d3899569e50324a8b159c193230fcd51ebaf2ce27d1d1bf8cfc03f7655e7eaecd1b31be3c4924eb9177a5ede62482a3d4e451043bc36b4249b24cd7806e10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
